serviceAccount: "%s"

artifacts:
  objects:
    location: "%s/{{domain}}"
    paths:
      - "*.pem"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: sh
    args:
      - -c
      - |-
        gcloud secrets versions access latest --secret=zerossl-email > zerossl-email.txt
        gcloud secrets versions access latest --secret=zerossl-apikey > zerossl-apikey.txt

  - name: certbot/dns-google
    entrypoint: sh
    args:
      - -c
      - |-
        apk add jq curl

        ZEROSSL_EMAIL=$$(cat zerossl-email.txt)
        ZEROSSL_APIKEY=$$(cat zerossl-apikey.txt)

        EAB=$$(curl -X POST "https://api.zerossl.com/acme/eab-credentials?access_key=$$ZEROSSL_APIKEY")
        EAB_KID=$$(echo $$EAB | jq -r .eab_kid)
        EAB_HMAC=$$(echo $$EAB | jq -r .eab_hmac_key)

        certbot certonly --non-interactive --dns-google \
        --server "https://acme.zerossl.com/v2/DV90" \
        --eab-kid "$$EAB_KID" --eab-hmac-key "$$EAB_HMAC" \
        --email "$$ZEROSSL_EMAIL" --agree-tos \
        --key-type ecdsa --elliptic-curve secp256r1 \
        --domains "{{domain}}" --domains "*.{{domain}}"

        cp -L /etc/letsencrypt/live/{{domain}}/*.pem .
